services:
  - type: web
    name: angielski-api
    runtime: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - package.json
        - pnpm-lock.yaml
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3
      pnpm install
      pnpm build 